# Generated by Django 2.1.5 on 2019-04-27 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(default='invalid annuncement', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm1', to='users.PropertyManager')),
            ],
        ),
    ]
