# Generated by Django 2.1.5 on 2019-04-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.TextField()),
                ('display', models.BooleanField(default=True)),
                ('Organization', models.CharField(max_length=100)),
                ('recievers', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announce', to='users.Tenant')),
            ],
        ),
    ]
