# Generated by Django 2.1.5 on 2019-04-27 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease', models.FileField(upload_to='leases/')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propm', to='users.PropertyManager')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ten', to='users.Tenant')),
            ],
        ),
    ]
