# Generated by Django 2.1.5 on 2019-04-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('is_resolved', models.BooleanField(default=False)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm', to='users.PropertyManager')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='users.Tenant')),
            ],
        ),
    ]
